# -*- coding: utf-8 -*-
from DbDefs import Table

class races(Table):
    table_name = 'Races'
    cols = ['unique_id','Name']
    colDefs = ['VARCHAR(20) UNIQUE','VARCHAR(50)']
    display_col = 1
    data = [
        ['elf','Elf'],
        ['dwarf','Dwarf'],
        ['human','Human'],
        ]

class classes(Table):
    table_name = 'Classes'
    cols = ['unique_id','Name','Minimum_Scores','Hit_Die_Type','Hit_Die_Max','Alignment','Experience_Bonus','Armour_Permitted','Shield_Permitted','Weapons_Permitted','Initial_Weapon_Proficiencies','Weapon_Proficiency_Advancement','Non-Proficiency_Penalty']
    colDefs = ['VARCHAR(20) UNIQUE','VARCHAR(50)','VARCHAR(50)','INTEGER','INTEGER','VARCHAR(20)','VARCHAR(20)','VARCHAR(20)','VARCHAR(20)','VARCHAR(20)','INTEGER','VARCHAR(20)','INTEGER']
    display_col = 1
    data = [
        ['assassin','Assassin','Str 12, Dex 12, Con 6, Int 11, Wis 6','6','15','Any Evil','None','Leather, Studded Leather','Leather, Studded Leather','Any','3','1 / 4','-3'],
        ['cleric','Cleric','Str 6, Dex 3, Con 6, Int 6, Wis 9, Cha 6','8','9','Any','Wis 16+','Any','Any','Blunt','2','1 / 3','-3'],
        ['druid','Druid','Str 6, Dex 6, Con 6, Int 6, Wis 12, Cha 15','8','14','Neutral Only','Wis and Cha 16+','Leather','Wooden','Club, dagger, dart, hammer, oil, scimitar, sling, spear, staff','2','1 / 3','-4'],
        ]

class items(Table):
    table_name = 'Items'
    cols = ['unique_id','Name']
    colDefs = ['VARCHAR(20) UNIQUE','VARCHAR(50)']
    display_col = 1
    data = [
        ['sword','Sword'],
        ]

class monsters(Table):
    table_name = 'Monsters'
    cols = ['unique_id','Name','Frequency','Number','Size','Move','AC','HD','Attacks','Damage','Special_Attacks','Special_Defences','Magic_Resistance','Lair_Probability','Intelligence','Alignment','Level/XP_Value','Treasure','Description']
    colDefs = ['VARCHAR(20) UNIQUE','VARCHAR(50)','VARCHAR(20)','VARCHAR(20)','VARCHAR(30)','VARCHAR(10)','INTEGER','VARCHAR(20)','INTEGER','VARCHAR(30)','VARCHAR(50)','VARCHAR(50)','VARCHAR(20)','VARCHAR(20)','VARCHAR(20)','VARCHAR(20)','VARCHAR(30)','TEXT','TEXT']
    display_col = 1
    data = [
        ['bandit','Bandit (Brigand)','Common','20d10','Man-sized','120ft','10','1d6 hp','1','By weapon','Leader types may have spells','None','Standard','20%','Mean (average to very)','Neutral (chaotic evil)','Variable','Individual 2d4 gp; Lair 1d6x1,000 cp (25%), 1d6x1,000 sp (30%), 1d6x1,000 ep (35%), 1d10x1,000 gp (40%), 1d4x100 pp (25%), 4d10 gems (60%), 3d10 jewellery (50%), 3 magic items (30%)','Bandits are found in almost any locale, for wherever there is a civilisation there will be those who prey upon the weak. There will always be higher level fighters found with large groups of bandits. Brigand: Brigands are a chaotic evil lot; otherwise they conform to the rules for bandits above. However they fight more fiercely in battle, and as a result receive a +1 morale bonus.'],
        ['berserker','Berserker','Rare','10d10','Man-sized','120ft','7','1d6+1 hp','1','By weapon','Leader types','Leader types','Standard','10%','Mean (average to very)','Neutral','Variable','Individual 3d6 sp; Lair 1d8x1,000 cp (50%), 1d6x1,000 sp (25%), 1d4x1,000 ep (25%), 1d3x1,000 pp (25%), 1d8 gems (30%), 1d4 jewellery (20%), 1 magic item (10%)','Berserkers are roaming bands of fighters. They are always unarmoured, as they see it as a sign of weakness. They fight with a fierce battle-lust, and as a result they may strike twice in a round or make one attack at +2. They never roll for morale checks once engaged in battle.'],
        ['buccaneer','Buccaneer (Pirate)','Uncommon','50d6','Man-sized','120ft','10','1d6 hp','1','By weapon','Leader types','Leader types','Standard','80% or 100%','Mean (average to very)','Neutral (chaotic evil)','Variable','Individual 3d6 sp; Lair 5d6x1,000 gp (60%), 1d8x100 pp (15%), 1d8x10 gems (60%), 5d8 jewellery (50%), 1 map (55%).','Buccaneers are found on all large bodies of water, their lair is most always the ship they use for raiding. pirate: Pirates are chaotic evil, but otherwise conform to buccaneers above.'],
        ['dervish','Dervish (Nomad)','Rare (Uncommon)','30d10','Man-sized','120ft','10','1d6 hp','1','By weapon','Leader types','Leader types','Standard','5% (15%)','Mean (average to very)','Lawful Good (neutral)','Variable','Individual 3d12 cp (2d6 ep); Lair 1d3x1,000 cp (20%), 1d4x1,000 sp (25%), 1d4x1,000 ep (25%), 1d4x1,000 gp (30%), 1d6x100 pp (30%), 1d6x10 gems (55%), jewellery (50%), 3 magic items (50%)','Dervishes are highly religious desert nomads. They will always be led by higher level fighters and clerics as follows. They are fanatical devotees to their religion. As a result they are at +1 to combat and never need to check morale. nomad: Nomads are mounted clans that live on steppes, plains or in desert climes. They live by hunting and gathering and are closely tied to their native climate. Due to their closeness with their surroundings, they surprise on 1-4.'],
        ['pilgrim','Pilgrim','Uncommon','10d10','Man-sized','120ft','10','1d6 hp','1','By weapon','Clerics','Clerics','Standard','Nil','Mean (average to very)','Variable','Variable','3d12 cp','Pilgrims are groups of religious followers making their way to some holy site. They can be encountered almost anywhere.'],
        ['merchant','Merchant','Common','50d6','Man-sized','120ft','10','1d6 hp','1','By weapon','Guards','Guards','Standard','Nil','Mean (average to very)','Neutral','Variable','3d12 cp, 3d6 sp, 2d6 ep, 2d4 gp, 1d6 pp, 2d4 gp (40%), 1d6x10 pp (50%), 4d8 gems (55%), 1d12 pieces of jewellery (45%).','Merchant encounters are actually caravans of merchants, drovers, and guards. The caravan will also contain pack animals, carts, and horses. Of the number appearing rolled, only about 10% will actually be merchants. 10% will be drovers and the last 80% will be the guards.'],
        ['dwarf','Dwarf','Common','40d10','Small (4 ft tall)','60ft','4','10','1','1d8 or by weapon','Leader types','Save vs poison and magic at 4 levels higher','As 4 levels higher','50%','Very','Lawful Good','2/30+1/hp','Individual: 2d4x5 gp; lair 10d4x1,000 gp (50%), 1d20x100 pp (50%), 5d4 gems (30%), 1d4x20 gems (50%), 1d10 jewellery (25%), any 4 magic items (15%)','Dwarfs are sturdy humanoids who live in extended clans. They typically make their homes in rocky hills.'],
        ['elf','Elf','Uncommon','20d10','Man-sized','120ft','5','1+1','1','1d8 or by weapon','+1 to hit with pulled bow or sword','Surprise on a roll of 1-4 on a d6','90% to sleep or charm only','10%','High','Chaotic Good','2/30+1/hp','1d6 pp','Sometimes elves live in a complex civilization, other times they are found living in wild bands. While there are several different types of elves, most do share the following traits.\n Elves live in a rather loose society where independent clans pledge their support to a central ruler. They will likely place their homes in a secluded thicket or meadow.'],
        ['gnome','Gnome','Rare','40d10','Small','60ft','5','1','1','1d6 or by weapon','+1 to hit vs kobolds and goblins','Large creatures -4 to hit vs gnomes;Save vs poison and magic at 4 levels higher','As 4 levels higher','50%','Very','Neutral to lawful good','1/10+1/hp','6d4 gp','Gnomes live underground in hills that they have burrowed into, seeking gems and precious metals. They are divided into clans which are rather competitive with each other, but are never outright hostile. They are a distant relative to dwarfs.'],
        ['halfling','Halfling','Rare','30d10','Small','90ft','7','1d6 hp','1','1d6 or by weapon','+3 to hit with bow or sling','Save vs poison and magic at 4 levels higher','As 4 levels higher','70%','Very','Lawful Good','1/5+1/hp','3d8 sp','Halflings as a race value hard work and simple living. Their settlements are as likely to contain small cottages as they are to have underground dwellings. They tend to keep to themselves and ask the same of other races.'],
        ['batrachian','Batrachian','Rare','10d8','Small to man-sized','30ft hop/150ft swim','6','1','1','By weapon','Hop','Camouflage','Standard','20%','Low to average','Chaotic Evil','1/18+1/hp','2d6 gp per individual, plus if encountered in their lair, a 20% chance of 1d3 pieces of jewellery and a 10% chance of 1d3 magic items','Batrachians represent the more advanced frog-man tribes, and are typically armed with spear and shield or harpoon and shield (treat their harpoons as spears). Batrachians can have shamans (maximum of 5th level) or witch doctors (maximum of 5th/4th level).'],
        ['batrachian_anu','Anuran','Rare','10d10','Small to man-sized','30ft hop/150ft swim','6','1','3','1d2/1d2/1d4+1','Hop','Camouflage','Standard','20%','Low','Chaotic Evil','1/15+1/hp','2d6 gp per individual, plus if encountered in their lair, a 20% chance of 1d3 pieces of jewellery and a 10% chance of 1d3 magic items','Anurans represent the less advanced frog-man tribes, and typically do not possess weapons or armour. Anurans can have shamans (maximum of 3rd level) or witch doctors (maximum of 3rd/2nd level). They otherwise count as batrachians.'],
        ['batrachian_fe','Batrachian Female','Rare','75% of no. of males','Small','30ft hop/150ft swim','6','1d6 hp','3','1d2/1d2/1d4','Hop','Camouflage','Standard','80%','Low to average','Chaotic Evil','1/10+1/hp','2d6 gp per individual, plus if encountered in their lair, a 20% chance of 1d3 pieces of jewellery and a 10% chance of 1d3 magic items','Females for both batrachians and anurans have the same stats.They are not normally combatant unless the efts or a temple, religious monument, or idol are threatened.'],
        ['batrachian_eft','Batrachian Eft','Very Rare','200% of no. of females','Small','150ft swim','8','1d2 hp','1','1d2','None','None','Standard','100%','Animal','Neutral','1/1','2d6 gp per individual, plus if encountered in their lair, a 20% chance of 1d3 pieces of jewellery and a 10% chance of 1d3 magic items','Efts are batrachian tadpoles. They are confined to water, and will always dwell in a large, central pool.'],
        ['bugbear','Bugbear','Uncommon','6d6','Large (7 ft tall)','90ft','5','3+1','1','2d8 or by weapon','Surprise on a 1-3 on 1d6','None','Standard','25%','Low to average','Chaotic Evil','3/135+4/hp','4d6 silver, 2d4 gold for individuals; 1d8x1,000 cp, 1d3x1,000 gp, 1d8 gems (30% chance), 1d4 jewellery (20% chance), miscellaneous magic weapon (10% chance)','Bugbears tend to form bands and live near goblins, a distant relative . Although bugbears have 60 ft infravision, they can live both above and below ground. Bugbears are quite stealthy and surprise at 50%; and a “hear noise”  roll will not detect them.'],
        ['caveman','Caveman','Rare','10d10','Man-sized','120ft','8','2','1','By weapon','None','None','Standard','40%','Low','Neutral','2/20+2/hp','Ivory tusks, gold nuggets, or uncut gems (5% chance per 10 cavemen present). The value of each is 1,000 gp per ivory tusk (2d6 tusks), 5 gp gold nuggets (2d4x10), and 10 gp gems (1d%)','Cavemen are primitive tribal humans living beyond the reach of normal civilisation. Hunting parties of cavemen (10 or more) are led by a 3rd level fighter.'],
        ['tribesman','Tribesman','Rare','10d12','Man-sized','120ft','7','1','1','By weapon','None','None','Standard','40%','Low to average','Neutral','1/10+10/hp','Ivory tusks, gold nuggets, or uncut gems (5% chance per 10 cavemen present). The value of each is 1,000 gp per ivory tusk (2d6 tusks), 5 gp gold nuggets (2d4x10), and 10 gp gems (1d%)','Tribesmen are usually found in tropical jungles, or remote islands. They use large wooden shields, and have the same leadership as cavemen.'],
        ['gnoll','Gnoll','Uncommon','20d10','Large','90ft','5','2','1','2d4 or by weapon','None','None','Standard','20%','Low to average','Chaotic Evil','2/30+2/hp','Individual 2d6 ep, 2d4 gp; Lair 1d8x1,000 cp (60%), 1d6x1,000 sp (50%), 1d8x1,000 ep (35%), 1d6x1,000 gp (50%), 5d4 gems (30%), 1d6 jewellery (25%), 2d4 potions (40%)','Gnolls are large hyena-faced creatures. They are covered in a grey fur with a dark muzzle and yellow mane. They have dark eyes, and long nails. Their armour is usually a mismatch of types taken from their victims. They have a rough life, and their average lifespan is only 35 years. Gnolls live and travel in small bands. They sometimes form loose alliances with other gnolls. They are very adaptive and can be found in most climes. There are rumours of a gnoll overlord, though if he exists his power and reach are limited.'],
        ['flind','Flind','Rare','2d12','Man-sized','120ft','5','2+3','1','2d4 or by weapon','Disarm','None','Standard','20%','Average','Chaotic Evil','2/40+4/hp','1d6 gp per individual; in lair: 1d6x1,000 cp (30%); 1d6x1,000 sp (25%); 2d4x1,000 ep (35%); 1d10x1,000 gp (45%); 1d4x100 pp (20%); 5d8 gems (50%); 4d12 jewellery (65%); 25%  chance of any 3 maps or magic','Flinds are close relatives of, and to a degree resemble, gnolls. Flinds stand 61⁄2 ft tall, with powerful limbs and a leonine head. Both flinds and gnolls regard flinds as more highly evolved beings and any gnoll will regard a flind as having 16 charisma. Groups of gnolls are often led by one or more flinds and the gnolls will obey any order given by a flind without question.'],
        ['goblin','Goblin','Uncommon','40d10','Small (4 ft tall)','60ft','6','1-1','1','1d6 or by weapon','None','None','Standard','40%','Average (low)','Lawful Evil','1/10+1/hp','Individual 3d6 sp ; Lair 1d12x1,000 cp (75%), 1d6x1,000 sp (50%), 1d6 gems (25%), 1d3 jewellery (20%), 2d4 potions (40%)','Goblins are small evil creatures with red eyes and a yellow to red coloured skin tone. They typically wear leather armour. They have an average lifespan of 50 years.'],
        ['grimlock','Grimlock','Uncommon','20d10','Man-sized','120ft','5','2','1','1d6 or by weapon','None','Save as 6th level fighter; +1 surprise','Special','75%','Average','Neutral Evil','2/28+2/hp','1d6x1,000 cp (25%), 1d4x1,000 sp (25%), 2d10x100 gp (25%), 1d8 gems (25%), 1d4 jewellery (25%) and 1 magic item (10%, armour or weapon only)','Grimlocks are a fierce race that dwell in the dark and hidden places of the earth, periodically issuing forth to the surface in search of prey, preferably human. Whilst somewhat resembling men in shape, they have a thick, almost scaly, hide that is a dusky grey in colour, a head of wild and matted black hair, a mouthful of vicious pointed teeth and two white featureless orbs for eyes. Though it is unknown whether grimlocks speak a language, it is certain that they are entirely blind as a race.'],
        ['hobgoblin','Hobgoblin','Uncommon','20d10','Man-sized (6½ ft tall)','90ft','5','1+1','1','1d8 or by weapon','None','None','Standard','25%','Average','Lawful Evil','2/20+2/hp','Individual 3d12 cp, 2d8 gp; Lair 1d8x1,000 cp (75%), 1d12x1,000 sp (60%), 1d8x1,000 ep (35%), 1d6x1,000 gp (50%), 5d4 gems (50%), 1d6 jewellery (25%), 1 potion (15%)','Hobgoblins are larger, hairier goblins with brown to grey fur. They have bright red or orange faces and yellow or brown coloured eyes. They have an average lifespan of 60 years.'],
        ['kobold','Kobold','Uncommon','40d10','Small (3 ft tall)','60ft','7','1d4 hp','1','1d4 or by weapon','None','None','Standard','40%','Average (low)','Lawful Evil','1/5+1/hp','Individual 3d6 cp; Lair 1d4x1,000 cp (50%), 1d3x1,000 sp (30%), 1d4 gems (50%)','Kobolds stand 3 ft tall and have a dark skin tone (brown to black), with no hair. They are vaguely reptilian in appearance with scales, small horns on their heads, short snaky tails and red eyes. They have an average lifespan of 135 years.'],
        ['lizard_man','Lizard Man','Rare','10d4','Man-sized (7 ft tall)','60ft, swimming 120ft','5','2+1','3','1d2/1d2/1d8','None','None','Standard','30%','Low (average)','Neutral','2/20+2/hp','Lair 1d8x1,000 cp (10%), 1d12x1,000 sp (15%), 1d8x1,000 ep (15%), 1d6x1,000 gp (50%), 1d10 gems (30%), 1d6 jewellery (25%), 2 magic items or 1 potion (15%)','Their hides are tough and leathery, and are colored in many different shades of green. They have cold black eyes, and hard nails on their fingers. Some have a bony ridge along their backs. Lizard men speak their own tongue, and a few (10%) can also speak common.'],
        ['orc','Orc','Common','30d10','Man-sized (6ft tall)','90ft','6','1','1','1d8 or by weapon','None','None','Standard','35%','Average (low)','Lawful Evil','1/10+1/hp','Individual 2d6 ep ; Lair 1d12x1,000 cp (50%), 1d6x1,000 sp (40%), 1d6 gems (25%), 1d3 jewellery (20%), 2d4 potions (40%)','Orcs are filthy, disgusting creatures with a brown or brownish-green coloured skin tone. Their hair is a nest of black or dark brown. They wear rusty and misused armour. They have an average lifespan of 40 years.'],
        ['troglodyte','Troglodyte','Common','10d10','Man-sized','120ft','5','2','3','1d3/1d31d4+1 or by weapon','Repulsive odour','None','Standard','15%','Low','Chaotic Evil','2/20+2/hp','Individual 2d6 ep; Lair 1d6x1,000 cp (25%), 1d6x1,000 sp (30%), 1d6x1,000 ep (35%), 1d10x1,000 gp (40%), 1d4x100 pp (25%), 4d10 gems (60%), 3d10 jewellery (50%), 3 magic items (30%)','Troglodytes are a tribal race of reptilians that make their lairs deep underground. They have infravision (90 ft range). They have an unnatural hatred of humans, and will attack them on sight. Troglodyte skin is normally a dark green colour. However, they have the ability to alter this colouration depending on the area around them (much like a chameleon). This ability allows them to surprise others on a 1-4. This surprise bonus does not work when they are emitting their odour. They have bony fins along their skulls, and dark reptilian eyes.'],
        ['cyclops','Cyclops','Very Rare','1d2','Large (20 ft tall)','150ft','2','13','1','6d6 or 4d10','Rock throwing','None','Standard','80%','Low','Chaotic Evil','7/3300+17/hp','1d10x1,000 cp (5%), 1d12x1,000 sp (25%), 1d6x1,000 ep (25%), 1d8x1,000 gp (25%), 1d12 gems (15%), 1d8 jewellery (10%), 3 magic items (25%), 2d8 potions and 1 scroll (40%)','Cyclopes are extremely tall, ugly humanoids, each with a single eye centred under its slightly drooping brow. These oafish, antisocial creatures prefer to inhabit lonesome environs, such as out-of-the-way, otherwise deserted islands.'],
        ['giant_cloud','Giant, Cloud','Rare','1d6','Large (18 ft tall)','150ft','2','12+1d6+1','1','6d6','Rock throwing','Levitate (Very Intelligent only)','Standard','40%','Average up to very','Neutral Good (50%)/Neutral Evil (50%)','8/3520+16/hp','10d4x100 gp, 4d6 + 6 gems (15%), 1d8 jewellery (10%), 4 magic items (25%)','Cloud giants usually live in giant castles at high elevations. When not high up in the mountains, their castles are on clouds given substance by magic. The majority (90%) of giants have average intelligence; the remainder are very intelligent and most often live in castles in the sky. Cloud giants often dress in flowing clothing and fancy jewellery. They have bronze to white hair, with skin in tones of blue ranging from nearly white to cold, light blue.'],
        ['giant_fire','Giant, Fire','Uncommon','1d8','Large (12 ft tall)','120ft','3','11+1d4+1','1','5d6','Rock throwing','Rock catching (50%)','Standard','35%','Low up to average','Lawful Evil','7/2720+16/hp','10d4x100 gp, 1d12 gems (15%), 1d8 jewellery (10%), 4 magic items (25%)','Like cloud giants, fire giants often live in castles (50%), but are just as likely to frequent caves. Fire giants’ hair is the red and orange colour of flames, and their skin is soot black. Their teeth are flame orange, and their eyes red. The commonly wear armour on their broad, 6 foot wide shoulders. This armour is sometimes made from the skin of dragons.'],
        ['giant_frost','Giant, Frost','Rare','1d8','Large (15 ft tall)','120ft','4','10+1d4','1','4d6','Rock throwing','Rock catching (40%), Cold immunity','Standard','30%','Low up to average','Chaotic Evil','7/1820+14/hp','10d4x100 gp, 1d12 gems (15%), 1d8 jewellery (10%), 4 magic items (25%)','Frost giants get their name from their love of the cold. They often live within frosty caverns, but also have a propensity to take up residence in castles, as do some of their other giant kin. This love of the cold is reflected in the fact that frost giants are completely immune to ill effects from cold, including the bone-chilling breath of white dragons. Frost giants have the overall appearance of giant, muscled barbarians. They have light yellow or blue eyes, with white hair that can likewise be tinged with yellow or blue.'],
        ['giant_hill','Giant, Hill','Common','1d10','Large (10 ft 6 in tall)','120ft','4','8+1d2','1','2d8','Rock throwing','Rock catching (30%)','Standard','25%','Low','Chaotic Evil','6/1200+12/hp','2d10x100 gp, 1d10 gems (30%), 1d6 jewellery (25%), 3 magic items (15%)','Hill giants live in mostly inhospitable locations. Half of the time hill giants have other animals or beings guarding their homes. In many ways hill giants resemble larger ogres, including having eyes red-rimmed, and they will often wield some type of bludgeoning weapon. In fact, hill giants frequently (50%) also speak the language of ogres. They have skin of rust brown or tan, with similarly coloured rust or black hair. They dress in animal skins.'],
        ['giant_stone','Giant, Stone','Uncommon','1d8','Large (12 ft tall)','120ft','0','9+1d4','1','3d6','Rock throwing','Rock catching (90%)','Standard','30%','Average','Neutral','7/1500+14/hp','2d10x100 gp, 1d10 gems (30%), 1d6 jewellery (25%), 3 magic items (15%)','Stone giants live in mountainous locations exclusively in caverns or otherwise in the earth. They are most active at night. Stone giants are partially named for their stone-like complexions and iron coloured eyes. Their hair is also dark-stone coloured, sometimes with hints of blue. Whereas hill giants often use wooden clubs, stone giants prefer stone and wear skins the colour of stone.'],
        ['giant_storm','Giant, Storm','Rare','1d4','Large (21 ft tall)','150ft','1','15+1d6+1','1','7d6','Spell-like abilities','Electricity immunity, breathe/function underwater normally','Standard','30%','Exceptional','Chaotic Good','9/6000+20/hp','10d4x100 gp, 4d6 + 6 gems (15%), 1d8 jewellery (10%), 4 magic items (25%)','Storm giants are the most formidable of giants in many campaigns. Storm giants are too intelligent, sophisticated, and magically endowed to toss rocks like their brethren. Instead, storm giants can employ the following spell-like abilities once per day: lightning bolt (8d8 damage), call lightning (10 to 15d6 damage, 3 bolts), control winds, predict weather, and weather summoning. Further, they can levitate their own weight plus an additional weight equal to 30,000 gold pieces two times per day. Storm giants can breathe and otherwise function underwater unimpeded. They are immune to all damage by electricity, including the fearsome electrical bolt breathed by the dreaded blue dragon. There are two typical appearances of storm giants, related to their preference for environment. Those who choose to live under water are often of green hair, eyes and skin, while those above water have purple skin, eyes either purple or cloudy grey, and blue-tinted black hair.'],
        ['ettin','Ettin','Very Rare','1d4','Large (13 ft+)','120ft','3','10','2','2d8/3d6','None','None','Standard','20%','Low','Chaotic Evil','7/1370+14/hp','Individual: 2d10 gp, 1d6 gems (25%), 1d4 jewellery (20%) 2 magic items; Lair: 2d6x1,000 gp (70%)','Ettins are dirty creatures that wear tattered skins and often use wicked weapons, such as barbed clubs. They share some affinity to orcs, witnessed in their pig-like faces.'],
        ['ogre_com','Ogre, Common','Common','2d10','Large (9 ft+)','90ft','5','4+1','1','1d10 or weapon','None','None','Standard','20%','Low','Chaotic Evil','3/95+5/hp','Individual: 20d4 gp; Lair: 1d3x1,000 gp (30%), 5d8 gems (40%), 2 magic items (10%), 2d4 potions (40%)','Ogres are malicious beings who live in all environments, whether above or below ground. They have affinity with hill giants and trolls, and often can be found with them. Additionally, ogres love wealth, and will hire themselves out to other creatures toward this end.'],
        ['ogre_mag','Ogre, Mage','Rare','1d6','Large (9 ft+)','90ft,150 ft flying (AA: level III)','4','5+2','1','1d12 or weapon','Special','Special','Standard','25%','Average to high','Chaotic Evil','5/750+6/hp','2d10x1,000 gp (50%), 1d10x1,000 pp (50%), 3d6 gems (25%), 1d6 jewellery (25%), 1d6 potions (100%) and 1d6 magic items (25%)','Ogre magi are fearsome evil creatures, well versed in magic and of unnatural size and strength. They stand around nine or ten feet tall, are thick-limbed, wide of girth and heavily muscled, but otherwise more or less resemble men in shape. Ogre magi are known to have thick skin that usually ranges in colour from pale yellow to brown or black, but some are said to be green or even blue. Most have reddish coloured eyes, two or more yellow to white horns, thick tusks, sharp yellow to black nails and long dark hair. They speak common and ogrish, amongst other languages.'],
        ['troll','Troll','Uncommon','1d12','Large (9 ft + tall)','120ft','4','6+6','3','1d4+4/1d4+4/2d6','See below','Regeneration','Standard','40%','Low','Chaotic Evil','6/525+8/hp','Lair 1d8x1,000 cp (10%), 1d12x1,000 sp (15%), 1d8x1,000 ep (15%), 1d6x1,000 gp (50%), 1d10 gems (30%), 1d6 jewellery (25%), 2 magic items or 1 potion (15%)','Trolls are vile, putrid creatures found in almost any climate. They can attack up to three opponents at a time using their powerful limbs to claw and their wicked teeth for biting. After three rounds of combat, their innate regeneration ability will start working, recovering 3 hit points per round. Their ability to regenerate even allows detached limbs to reattach to their body. Severed limbs will even continue to attack foes independently. A troll can only be truly destroyed by fire or acid, and these type of damage cannot be regenerated.'],
        ['troll_gi','Troll, Giant','Rare','1d12','Large (10 ft tall)','120ft','4','8','1','2d8','Nil','Regeneration','Standard','33%','Low','Chaotic Evil','6/750+10/hp','2d6x1,000 cp (20%), 1d6x1,000 sp (35%), 1d4x1,000 ep (15%), 1d6 gems (25%), 1d4 jewellery (25%), any 2 maps or magic (10%)','These horrible creatures are the result of crossbreeding trolls with hill giants, resulting in a monster that looks like a troll combined with the large size and pot-belly of a hill giant. The hide of a giant troll is reddish brown and they have tough wiry black hair, bulbous nose, and red rimmed eyes.'],
        ]

class classes_meta(Table):
    table_name = 'Classes_meta'
    cols = ['class_id','Type','Level','XP','Hit_Dice','Notes','Casting_Level','Level_1_Spells','Level_2_Spells','Level_3_Spells','Level_4_Spells','Level_5_Spells','Level_6_Spells','Level_7_Spells','Level_8_Spells','Level_9_Spells','Aimed_Magic_Items','Breath_Weapons','Death_Paralysis_Poison','Petrifaction_Polymorph','Spells','To_Hit_-10','To_Hit_-9','To_Hit_-8','To_Hit_-7','To_Hit_-6','To_Hit_-5','To_Hit_-4','To_Hit_-3','To_Hit_-2','To_Hit_-1','To_Hit_0','To_Hit_1','To_Hit_2','To_Hit_3','To_Hit_4','To_Hit_5','To_Hit_6','To_Hit_7','To_Hit_8','To_Hit_9','To_Hit_10','Climb_Walls','Find_Traps','Hear_Noise','Hide_in_Shadows','Move_Quietly','Open_Locks','Pick_Pockets','Read_Languages','Ability','Level_Gained','Ability_Description']
    colDefs = ['VARCHAR(50) REFERENCES Classes(unique_id) ON UPDATE CASCADE ON DELETE CASCADE','VARCHAR(20)','INTEGER','INTEGER','INTEGER','VARCHAR(50)','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','INTEGER','VARCHAR(20)','INTEGER','TEXT']
    display_col = 0
    data = [
        ['assassin','xp table','1','0','1','','0','0','0','0','0','0','0','0','0','0','14','16','13','12','15','26','25','24','23','22','21','20','20','20','20','20','20','19','18','17','16','15','14','13','12','11','80','25','10','20','20','30','35','1','','',''],
        ['assassin','xp table','2','1600','2','','0','0','0','0','0','0','0','0','0','0','14','16','13','12','15','26','25','24','23','22','21','20','20','20','20','20','20','19','18','17','16','15','14','13','12','11','80','25','10','20','20','30','35','1','','',''],
        ['assassin','xp table','3','3000','3','','0','0','0','0','0','0','0','0','0','0','14','16','13','12','15','26','25','24','23','22','21','20','20','20','20','20','20','19','18','17','16','15','14','13','12','11','80','25','10','20','20','30','35','1','','',''],
        ['assassin','xp table','4','5750','4','The assassin may recruit assassins as henchmen','0','0','0','0','0','0','0','0','0','0','14','16','13','12','15','26','25','24','23','22','21','20','20','20','20','20','20','19','18','17','16','15','14','13','12','11','82','29','13','25','25','34','39','5','','',''],
        ['assassin','xp table','5','12250','5','','0','0','0','0','0','0','0','0','0','0','12','15','12','11','13','24','23','22','21','20','20','20','20','20','20','19','18','17','16','15','14','13','12','11','10','9','84','33','16','30','30','38','43','10','','',''],
        ['assassin','xp table','6','24750','6','','0','0','0','0','0','0','0','0','0','0','12','15','12','11','13','24','23','22','21','20','20','20','20','20','20','19','18','17','16','15','14','13','12','11','10','9','86','37','19','35','35','42','47','15','','',''],
        ['assassin','xp table','7','50000','7','','0','0','0','0','0','0','0','0','0','0','12','15','12','11','13','24','23','22','21','20','20','20','20','20','20','19','18','17','16','15','14','13','12','11','10','9','88','41','22','40','40','46','51','20','','',''],
        ['assassin','xp table','8','99000','8','The assassin may recruit thieves as henchmen','0','0','0','0','0','0','0','0','0','0','12','15','12','11','13','24','23','22','21','20','20','20','20','20','20','19','18','17','16','15','14','13','12','11','10','9','90','45','25','45','45','50','55','25','','',''],
        ['assassin','xp table','9','200500','9','Master Assassin','0','0','0','0','0','0','0','0','0','0','10','14','11','10','11','21','20','20','20','20','20','20','19','18','17','16','15','14','13','12','11','10','9','8','7','6','91','49','28','50','50','54','59','30','','',''],
        ['assassin','xp table','10','300000','10','','0','0','0','0','0','0','0','0','0','0','10','14','11','10','11','21','20','20','20','20','20','20','19','18','17','16','15','14','13','12','11','10','9','8','7','6','92','53','31','55','55','58','63','35','','',''],
        ['assassin','xp table','11','400000','11','','0','0','0','0','0','0','0','0','0','0','10','14','11','10','11','21','20','20','20','20','20','20','19','18','17','16','15','14','13','12','11','10','9','8','7','6','93','57','34','60','60','62','67','40','','',''],
        ['assassin','xp table','12','600000','12','The assassin may recruit henchmen of any class','0','0','0','0','0','0','0','0','0','0','10','14','11','10','11','21','20','20','20','20','20','20','19','18','17','16','15','14','13','12','11','10','9','8','7','6','94','61','37','65','65','66','71','45','','',''],
        ['assassin','xp table','13','750000','13','','0','0','0','0','0','0','0','0','0','0','8','13','10','9','9','20','20','20','20','20','19','18','17','16','15','14','13','12','11','10','9','8','7','6','5','4','95','65','40','70','70','70','75','50','','',''],
        ['assassin','xp table','14','1000000','14','Guildmaster','0','0','0','0','0','0','0','0','0','0','8','13','10','9','9','20','20','20','20','20','19','18','17','16','15','14','13','12','11','10','9','8','7','6','5','4','96','69','43','75','75','74','79','55','','',''],
        ['assassin','xp table','15','1500000','15','Grandmaster Assassin','0','0','0','0','0','0','0','0','0','0','8','13','10','9','9','20','20','20','20','20','19','18','17','16','15','14','13','12','11','10','9','8','7','6','5','4','97','73','46','80','80','78','83','60','','',''],
        ['assassin','ability','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','Assassination','1','If an assassin gains surprise he or she may elect to assassinate the victim. The assassin need not roll to hit for an assassination attempt, which is a special attack resulting in a chance to kill the victim instantly and ensure damage even if the victim is not successfully killed. The percentage chance to kill a victim is 50%, with a bonus of 5% per level of the assassin and a penalty of 5% for every two levels of the target (rounding down; in the case of monsters, substitute “hit dice” for “level”). These numbers are approximate, for the GM should modify the assassin’s chances slightly upward or downward according to the circumstances—guarded or wary targets are less likely to be killed, and unwary victims are more likely to die. If the assassination attempt does not succeed, the attack still inflicts normal damage, together with any applicable bonuses. The assassin does not gain backstab multiple damage on a failed assassination attempt, even if the assassination attempt was made from behind.'],
        ['assassin','ability','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','Backstab','1','An assassin may backstab with any of the melee weapons permissible to the thief class. Backstabbing doubles the weapon’s damage at levels 1-4, triple at levels 5-8, quadruple at level 9-12, and so on. Also, an assassin attacks from behind with a bonus to hit of +4 rather than the ordinary +2.'],
        ['assassin','ability','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','Disguise','1','Assassins are masters of disguise. Within reasonable limits, an assassin can make him- or herself appear slightly shorter or considerably taller, fatter or thinner, or of the opposite gender. An assassin can even disguise him- or herself as a member of another race (again, within reason). Any person observing the disguised assassin has a base 2% chance to see through the disguise, with one chance per day to do so. The base chance of seeing through a disguise increases another 2% if the assassin is posing as another class, race or gender (max 8% chance). The GM may assign additional penalties and bonuses to this check if the observer is unusually wise or intelligent (or particularly stupid), and common sense, of course, applies at all times.'],
        ['assassin','ability','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','Poison','1','Assassins are not inherently better at using poison than any other character class capable of using poison, but generally have more opportunities to gain knowledge of poisons and their effects.'],
        ['assassin','ability','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','Thief Abilities','1','The assassin has thief abilities as a thief two levels below the assassin’s level. At first level, the assassin has the thieving abilities of a first level thief, but does not gain the abilities of a second level thief until reaching fourth level.'],
        ['assassin','ability','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','Languages','9','Ninth and higher-level assassins with Int 15+ may learn languages that it would be impossible for a non-assassin to learn. An assassin can learn an alignment tongue other than his or her own, druids’ cant, and thieves’ cant as additional languages, but can only learn a maximum of four such special languages, one for each point of intelligence above 14. Only one such language can be learned per level above eighth. Such languages are over and above any limits imposed by the assassin’s race and intelligence.'],
        ['assassin','ability','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','Read Scrolls','12','When an assassin reaches 12th level, he or she has received sufficient training to cast spells from an arcane scroll (magic user or illusionist).'],
        ]

